In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.8

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  7.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0. -2.  0.  0.

In [5]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state 
# 1 is state to the right of 0
# 2 is the snake-pit state 
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions 
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.  -1.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.   0.   0.   0.  -1.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.  10.   0.   0.  -1.]
 [  0.   0.   0.  10.  -1.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.  -1.  -1.]
 [ 

(1) \
시작 상태를 0으로 설정한 후, 목표 상태에 도달할 때까지 반복 \
현재 상태에서 랜덤하게 하나의 유효한 행동을 선택 \
선택한 행동을 수행하고 다음 상태를 찾음 \
다음 상태에서 가능한 모든 행동에 대한 Q-값을 가져와 max값을 선택 \
현재 상태의 Q-값 갱신 \
(2) \
감마를 0.5로 낮췄을 때, 현재 보상을 더 중요하게 여기기 때문에 Q-값이 전반적으로 작아짐

